### PR TITLE
Master

### PR DESCRIPTION
**Pull request by dwelch91**
* Safe(r) `*`, `**`, `<<`, etc
* Recursion limiter
* Runtime limiter
* PEP8
* Streamlined tests
* Some additional escape tests
* Allow tests to run w/o numpy
* Full Py3 and Py2 support

### CODE REVIEW

**Comment by dwelch91** [comment]
Sorry, commit b2c6943 has an incorrect commit message. Should read: `3.4 not avail. on travisci, ...`

**Comment by newville** [comment]
@dwelch91  Thanks so much!! That all looks really great.  Sorry for the delay, I was away for a few weeks, just getting back with many "real job" emergencies.   

I had been thinking that a DOS attack would need a separate timer thread, but I like the idea of checking at the top of each "run()" too and limiting values for "operations known to be potentially slow" is much simpler and will catch many, many errors.

I think these are really great improvements and my inclination is to merge as is unless you know of some reason to hold off. I think this should cause a version bump, with the new features (especially the `max_time` argument to `Interpreter()`) documented.    Are you willing / able to add to the sphinx docs, or should I?  

FWIW, the travis script might need changing to be more like https://github.com/lmfit/lmfit-py/blob/master/.travis.yml to work with Python 3.5.   It would be good to test for Python <3.5 and 3.5,  as there were changes in the ast nodes for Call() in Python 3.5.  But that (adding Python3.5 to the travis config) is probably a separate issue.  

Thanks again!

**Comment by dwelch91** [comment]
Hi, Matt-
I don't have any particular reason to hold off merging, so I'd say go ahead
and do it when you are able/comfortable with it. I didn't make any changes
to the sphinx docs... I guess I'd request that you update them if you
wouldn't mind, I'd have to come up to speed with this format and tooling
first anyway.
I don't have much experience with TravisCI, so if you want to add more
tests for 3.5, etc. please go right ahead, that seems like a great idea.
Our shop uses 3.4, so that was the important version for our needs.
Thanks,
Don

**Comment by newville** [comment]
@dwelch91 Will do.  Thanks again!!

**Pull request merged**
