### PR TITLE
Don't raise AttributeError when using partials

### PR DESCRIPTION
**Pull request by chrisjbremner**
I ran into an issue recently where I passed in a partial function into the symbol table, and then ran a method that raised an `Exception`. Instead of raising the `Exception` I expected, I instead encountered a `AttributeError` due to `functools.partial` objects not having a `__name__` attribute. This is best illustrated by example:

Before:
```python
In [1]: from functools import partial

In [2]: import math

In [3]: import asteval

In [4]: aeval=asteval.Interpreter()

In [5]: aeval.symtable["sqrt"] = partial(math.sqrt)

In [6]: aeval("sqrt(-1)")
AttributeError
   sqrt(-1)
'functools.partial' object has no attribute '__name__'
```

After:
```python
In [1]: from functools import partial

In [2]: import math

In [3]: import asteval

In [4]: aeval=asteval.Interpreter()

In [5]: aeval.symtable["sqrt"] = partial(math.sqrt)

In [6]: aeval("sqrt(-1)")
ValueError
   sqrt(-1)
Error running function call 'functools.partial(<built-in function sqrt>)' with args [-1] and kwargs {}: math domain error
```

### CODE REVIEW

**Comment by newville** [comment]
@chrisjbremner Thanks for catching this!

**Comment by chrisjbremner** [comment]
@newville No problem. How's it look? Anything I should fix before we merge?

**Comment by newville** [comment]
@chrisjbremner  Well, I think using `func_name = getattr(func, '__name__',  str(func))` would be cleaner.  Do you agree?  If so, make that change and I'll merge....

**Comment by chrisjbremner** [comment]
Agreed, done. Happy Thanksgiving!

**Comment by newville** [comment]
@chrisjbremner   Great, thanks!

**Pull request merged**
