### PR TITLE
Add degree argument trig. functions

### PR DESCRIPTION
**Pull request by gwiskur**

### CODE REVIEW

**Comment by newville** [comment]
@gwiskur A couple of thoughts here:

1.  neither `math` nor `numpy` modules support these functions, and require arguments to be in correct, dimensionless units.  That is, why would someone expect there to be a function `acos_d()`?   And should that be `acos_d()` or `acosd()`?  Either there is a clear precedent so that it is "obvious" or they have to look it up, at which point, why not use the correct dimensions?

2. if we add these from `math`, they should also be added from `numpy`, if available.  

I'm leaning "no" on this, but I might be persuaded otherwise.  The functions `degrees()` and `radians()` are available: why not just use those?

**Comment by gwiskur** [comment]
@newville Things to consider:

1. [Matlab](https://www.mathworks.com/help/matlab/ref/acosd.html?requestedDomain=www.mathworks.com), [Octave](https://www.gnu.org/software/octave/doc/v4.0.1/Trigonometry.html#XREFacosd), & [Scilab](https://help.scilab.org/docs/6.0.0/en_US/acosd.html) feature these functions, so the syntax should probably be `acosd()` to follow their convention.  The appended "d" seems intuitive.  It is convenient and concise to have dedicated degree-trig functions; asteval may be more likely to be employed in applied mathematics and engineering use-cases, where degree units are more common, than other python use-cases.
2. Probably should be added from both `math` & `numpy`; Is one a fallback for the other?

**Comment by newville** [comment]
@gwiskur 

1.  asteval is not really trying to emulate languages other than Python.  IIUC, Python doesn't have `acosd` etc in either `math` or `numpy` (actually, `numpy` uses `arccos`, but that's another story).    That's not to say we should not add these, but well, are they needed?   I guess I'm not actually opposed, but if we do add them, we should at least get the spelling correct....

For spelling, if `acosd` is preferred, why does the code in the PR use both `acosd` and `acos_d`?  Shouldn't they be consistent?

I don't really know who is using asteval.  It seems most questions are about preventing or killing long-running calculations, or restricting the available code constructs, so seem to be related to web contexts.  I use it in math/science/engineering context, but also expect trig functions to use radians.

2. Definitely as: `numpy` if available, `math` if not.

So, I guess I'd say that if you fix these two points (consistent spelling in code, use numpy if available) and add some non-trivial tests, I'm willing to merge this.

**Comment by newville** [comment]
Sorry, this is not consistent with python syntax, and appears to not be a priority for anyone.

**Pull request closed without merging**
