### PR TITLE
fix pow int to negative exponent

### PR DESCRIPTION
**Pull request by ccomb**
Fixed `2**-2` case

### CODE REVIEW

**Comment by ccomb** [comment]
fixes #115

**Comment by newville** [comment]
@ccomb Thanks for catching this, fixing it, and adding a test!

**Comment by newville** [comment]
@ccomb Thanks for the reminder, I will push 0.9.30 in a few days. 

To be clear, this is a relatively small change compared to other recent changes -- mostly adding capabilities, and some documentation changes are still needed for those changes.

**Comment by newville** [comment]
@ccomb 0.9.30 is now released, with this fix

**Comment by ccomb** [comment]
\o/ Thanks a lot !!

**Pull request merged**
